name: Test package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10.12, 3.11]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install codecov
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python -m pytest --cov=truegaze/ --cov-report=xml
        codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
    - name: Test package build and install
      run: |
        python setup.py install
        truegaze scan test_data/helloworld.apk
        truegaze scan test_data/helloworld.ipa
